apiVersion: v1
kind: Service
metadata:
  name: pneumonia-classifier
spec:
  type: NodePort
  selector:
    app: pneumonia-classifier
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080